services:
  # jable-downloader-script:
  #   container_name: jable-downloader-script
  #   build: 
  #     context: .
  #   volumes:
  #     - ./downloads:/jable-downloader/downloads
  #   command: bash /jable-downloader/scripts/download-video.sh https://jable.tv/videos/ssis-798/ /jable-downloader/downloads

  jable-downloader-service:
    container_name: jable-downloader-service
    build: 
      context: .
    environment:
      # 0. 下载视频不做任何处理
      # 1. 快速无损转码，AAC ADTS 转 AAC，元数据挪到文件开头（JableTVDownload 作者推荐）
      # 2. 使用 N 卡加速，转码为 H.264，码率 10000K
      # 3. 使用 CPU 转码为 H.264，码率 3000K
      - ENCODING_TYPE=1
    volumes:
      - ./downloads:/app/downloads
      - ./docker-test/db:/app/db

  jable-downloader-ui:
    container_name: jable-downloader-ui
    build: 
      context: ./client
    environment:
      - API_ENDPOINT="http://jable-downloader-service:3000"
    ports:
      - 41056:80